### ISSUE TITLE
运行python main.py之后，提示没有scrapy.cmdline

### ISSUE THREAD

**Issue by RockZhou8** [hk029/LagouSpider#1]

**Comment by RockZhou8** [comment]
pip install 了 scrapy，现在提示
  File "c:\python27\lib\site-packages\twisted\internet_win32stdio.py", line 7, in <module>
    import win32api
ImportError: DLL load failed: %1 不是有效的 Win32 应用程序。

要装其他东西？VS?

**Comment by hardy4yooz** [comment]
童鞋，你的这个爬虫现在还好使吗?现在拉勾好像禁止爬虫呢。

**Comment by RockZhou8** [comment]
同问，好像我也遇到其他的爬拉勾失败的

2016年7月31日 00:24，"Hardy" notifications@github.com写道：
